begin;
create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions, pgtap;
select plan(4);
select ok(not has_function_privilege('authenticated','public.restore_device_account(text)','EXECUTE'),'device recovery is inaccessible even with SMS session');
select ok(not has_function_privilege('authenticated','public.claim_device_welcome_points(text)','EXECUTE'),'device balance cannot overwrite account wallet');
select ok(not exists(select 1 from pg_trigger where tgname='sync_active_device_wallet_after_balance'),'wallet no longer mirrors to a device');
select ok(has_function_privilege('authenticated','public.claim_account_welcome_points()','EXECUTE'),'account-scoped welcome claim exists');
select * from finish();
rollback;
