begin;

create extension if not exists pgtap with schema extensions;
set local search_path = public, extensions, pgtap;
select plan(47);

select has_table('public', 'profiles', 'profiles table exists');
select has_table('public', 'device_welcome_grants', 'device reward ledger exists');
select has_table('public', 'account_deletion_audit', 'account deletion audit exists');
select has_column('public', 'profiles', 'welcome_points_claimed', 'welcome claim guard exists');
select has_function('public', 'claim_device_welcome_points', array['text'], 'device welcome RPC exists');
select has_function('public', 'delete_account_data', array['uuid'], 'server deletion RPC exists');
select ok((select relrowsecurity from pg_class where oid = 'public.device_welcome_grants'::regclass), 'device ledger has RLS');
select ok(not has_function_privilege('anon', 'public.claim_device_welcome_points(text)', 'EXECUTE'), 'anon cannot claim points');
select ok(not has_function_privilege('authenticated', 'public.claim_device_welcome_points(text)', 'EXECUTE'), 'legacy device claim is disabled');
select ok(not has_function_privilege('authenticated', 'public.delete_account_data(uuid)', 'EXECUTE'), 'app user cannot run account cleanup directly');
select ok(has_function_privilege('service_role', 'public.delete_account_data(uuid)', 'EXECUTE'), 'service role can run account cleanup');
select ok(not has_table_privilege('authenticated', 'public.device_welcome_grants', 'SELECT'), 'app user cannot enumerate device hashes');
select has_table('public', 'device_point_wallets', 'device point wallets exist');
select has_table('public', 'device_wallet_bindings', 'device wallet bindings exist');
select has_table('public', 'message_backups', 'server-only message backups exist');
select has_function('public', 'restore_device_account', array['text'], 'device recovery RPC exists');
select has_function('public', 'admin_delete_message_backups', array['bigint[]', 'text'], 'owner backup deletion RPC exists');
select ok(not has_table_privilege('authenticated', 'public.device_point_wallets', 'SELECT'), 'app cannot enumerate device wallets');
select ok(not has_table_privilege('authenticated', 'public.message_backups', 'SELECT'), 'app cannot read message backups');
select ok(not has_function_privilege('authenticated', 'public.restore_device_account(text)', 'EXECUTE'), 'device identity cannot recover a phone account');
select has_column('public', 'messages', 'image_path', 'chat messages store a private image path');
select has_column('public', 'messages', 'image_width', 'chat messages store image width');
select has_column('public', 'messages', 'image_height', 'chat messages store image height');
select has_column('public', 'message_backups', 'image_path', 'message backups preserve chat image path');
select ok(exists(select 1 from storage.buckets where id = 'chat-images' and not public), 'chat image bucket is private');
select ok(exists(select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'chat members upload chat images'), 'chat image upload policy exists');
select ok(exists(select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'chat members read chat images'), 'chat image read policy exists');
select ok(exists(select 1 from pg_policies where schemaname = 'storage' and tablename = 'objects' and policyname = 'chat senders remove unsent images'), 'orphan chat image cleanup policy exists');
select ok(not has_column_privilege('authenticated', 'public.profiles', 'trust_score', 'UPDATE'), 'app cannot update profile trust score');
select ok(not has_column_privilege('authenticated', 'public.profiles', 'is_verified', 'UPDATE'), 'app cannot update profile verification');
select ok(not has_column_privilege('authenticated', 'public.profiles', 'status', 'UPDATE'), 'app cannot update profile account status');
select ok(has_function_privilege('authenticated', 'public.can_view_profile(uuid)', 'EXECUTE'), 'profile visibility predicate is available to authenticated RLS');
select ok(has_function_privilege('authenticated', 'public.can_send_room_message(uuid,uuid)', 'EXECUTE'), 'message send predicate is available to authenticated RLS');
select has_table('public', 'public_content_block_terms', 'public content block terms exist');
select has_function('public', 'is_public_content_blocked', array['text[]'], 'public content detector exists');
select ok(not has_table_privilege('authenticated', 'public.public_content_block_terms', 'SELECT'), 'app cannot enumerate public filter terms');
select ok(not has_function_privilege('authenticated', 'public.is_public_content_blocked(text[])', 'EXECUTE'), 'app cannot call internal public content detector');
select ok(public.is_public_content_blocked(array['조건 만남 하실 분']), 'filter normalizes spacing in prohibited terms');
select ok(not public.is_public_content_blocked(array['주말에 함께 전시 보실 분']), 'ordinary public conversation remains allowed');
select has_table('public', 'point_products', 'point purchase catalog exists');
select has_table('public', 'point_purchase_receipts', 'verified purchase receipt ledger exists');
select has_function('public', 'credit_verified_point_purchase', array['text', 'text', 'uuid', 'text', 'text', 'text', 'bigint', 'jsonb'], 'verified purchase credit RPC exists');
select has_function('public', 'refund_verified_point_purchase', array['text', 'text', 'jsonb'], 'verified purchase refund RPC exists');
select ok(not has_function_privilege('authenticated', 'public.credit_verified_point_purchase(text,text,uuid,text,text,text,bigint,jsonb)', 'EXECUTE'), 'app user cannot self-credit a purchase');
select ok(has_function_privilege('service_role', 'public.credit_verified_point_purchase(text,text,uuid,text,text,text,bigint,jsonb)', 'EXECUTE'), 'service role can credit verified purchases');
select ok(not has_function_privilege('authenticated', 'public.refund_verified_point_purchase(text,text,jsonb)', 'EXECUTE'), 'app user cannot forge purchase refunds');
select ok(has_function_privilege('service_role', 'public.refund_verified_point_purchase(text,text,jsonb)', 'EXECUTE'), 'service role can process verified refunds');

select * from finish();
rollback;
