import { Children, cloneElement, forwardRef, isValidElement, type ReactElement, type ReactNode } from 'react'
import { Text as NativeText, TextInput as NativeTextInput, type TextInputProps, type TextProps } from 'react-native'
import { boardAliasDisplayName } from '../lib/boardAlias'

let activeLanguage: 'ko' | 'en' = 'ko'
let activeCountry = 'KR'

export function setLocalizedUiLanguage(language: 'ko' | 'en', country: string = activeCountry) { activeLanguage = language; activeCountry = country }

const exact: Record<string, string> = {
  '잉톡': 'IngTalk', '닫기': 'Close', '취소': 'Cancel', '이전': 'Back', '저장': 'Save', '삭제': 'Delete', '수정': 'Edit', '전송': 'Send',
  '발견': 'Discover', '게시판': 'Board', '대화': 'Chats', '내 정보': 'My Info', '전체': 'All', '지역': 'Region', '동네': 'Local', '근처': 'Nearby', '내톡': 'Mine',
  '만남': 'Meetup', '애인': 'Dating', '영화': 'Movies', '음악': 'Music', '맛집': 'Food', '여행': 'Travel', '운동': 'Fitness', '게임': 'Games', '반려동물': 'Pets', '독서': 'Books', '카페': 'Cafes', '사진': 'Photos', '전시': 'Exhibitions', '드라마': 'TV',
  '수다': 'Chat', '취미': 'Hobbies', '친구': 'Friends', '연애': 'Dating', '고민상담': 'Advice', '식사': 'Dining', '산책': 'Walking',
  '남성': 'Male', '여성': 'Female', '기타': 'Other', '비공개': 'Private', '나': 'Me', '운영자': 'Admin', '잉톡 운영자': 'IngTalk Support',
  '허용 안 함': 'Not now', '다시 허용하기': 'Try again', '설정 열기': 'Open Settings', '기기 설정': 'Device Settings', '허용하기': 'Allow', '허용됨': 'Allowed', '설정에서 허용': 'Allow in Settings', '확인 중': 'Checking',
  '모두 동의합니다': 'Agree to all', '[필수]': '[Required]', '[선택]': '[Optional]', '본인은 만 19세 이상입니다': 'I am at least 19 years old', '서비스 이용약관 동의': 'Agree to the Terms of Service', '개인정보 처리방침 확인': 'Review the Privacy Policy', '위치 접근 권한': 'Location permission', '알림 수신 권한': 'Notification permission', '권한 확인 중…': 'Checking permissions…', '동의하고 시작하기': 'Agree and continue', '권한은 언제든 변경할 수 있어요': 'You can change permissions anytime', '내 정보의 권한 설정 또는 기기 설정에서 변경할 수 있습니다.': 'Change them in My Info or your device settings.',
  '성인 이용 확인': 'Adult eligibility', '서비스 이용약관': 'Terms of Service', '개인정보 처리방침': 'Privacy Policy', '위치 권한': 'Location permission', '알림 권한': 'Notification permission', '잉톡은 만 19세 이상만 이용할 수 있습니다. 동의하면 본인이 만 19세 이상이며 정확한 나이를 입력한다는 점을 확인합니다. 나이를 허위로 입력하거나 미성년자의 이용이 확인되면 계정과 콘텐츠가 제한 또는 삭제될 수 있습니다.': 'IngTalk is only for users age 19 or older. By agreeing, you confirm that you are at least 19 and will provide an accurate age. Accounts and content may be restricted or deleted for a false age or use by a minor.', '가까운 지역의 대화 상대를 추천하기 위해 앱을 사용하는 동안의 위치를 사용합니다. 정확한 좌표를 다른 사용자에게 공개하지 않으며, 동의하지 않으면 지역을 직접 선택할 수 있습니다.': 'Location is used while you use the app to suggest nearby people. Exact coordinates are never shown to other users. You can choose a region manually if you decline.', '새로운 대화 요청, 메시지, 신고 처리 결과와 중요한 서비스 안내를 기기에 알림으로 보내기 위해 사용합니다. 동의하지 않아도 앱을 열어 직접 확인할 수 있으며 기본 기능 이용에는 제한이 없습니다.': 'Notifications deliver chat requests, messages, report results, and important service updates. You can still check these in the app if you decline.',
  '프로필을 확인하고 있어요': 'Checking your profile', '프로필을 알려주세요': 'Tell us about you', '회원가입 없이 이 프로필로 바로 대화를 시작할 수 있어요.': 'Start chatting right away with this profile—no sign-up required.', '성인 전용 · 만 19세 이상': 'Adults only · Ages 19+', '미성년자는 가입하거나 이용할 수 없습니다.': 'Minors may not register or use this service.', '사진 변경': 'Change photo', '프로필 사진 등록': 'Add profile photo', '닉네임': 'Nickname', '2~9자로 입력': 'Enter 2–9 characters', '나이': 'Age', '세': 'years old', '만 19세 미만은 이용할 수 없습니다.': 'You must be at least 19 years old.', '19세 이상만 이용할 수 있어요.': 'Available to users ages 19 and older.', '성별': 'Gender', '프로필 만드는 중…': 'Creating profile…', '잉톡 시작하기': 'Start IngTalk', '임시 익명 ID로 안전하게 저장됩니다.': 'Saved securely with a temporary anonymous ID.', '데모 모드에서는 이 기기에만 저장됩니다.': 'Demo mode stores this only on this device.',
  '권한 설정': 'Permissions', '거리 표시와 사진·알림 기능에 필요한 권한을 관리합니다.': 'Manage permissions for distance, photos, and notifications.', '위치': 'Location', '알림': 'Notifications', '‹ 권한 설정': '‹ Permissions',
  '받고 싶은 알림과 알림 방식을 선택하세요.': 'Choose which notifications you receive and how they alert you.', '메시지 알림': 'Message notifications', '새 메시지가 도착하면 알려드려요.': 'Get notified when a new message arrives.', '대화 신청 알림': 'Chat request notifications', '새로운 대화 신청을 알려드려요.': 'Get notified about new chat requests.', '메시지 내용 미리보기': 'Message previews', '알림에 메시지 내용을 표시합니다.': 'Show message content in notifications.', '소리': 'Sound', '알림이 올 때 소리를 재생합니다.': 'Play a sound for notifications.', '진동': 'Vibration', '알림이 올 때 기기를 진동시킵니다.': 'Vibrate the device for notifications.', '같은 대화방의 연속 메시지는 하나의 알림 묶음으로 정리됩니다. 기기 자체 알림 설정이 꺼져 있으면 이 설정과 관계없이 알림이 표시되지 않습니다.': 'Consecutive messages from the same chat are grouped into one notification. Notifications will not appear if they are disabled in device settings.',
  '회원 탈퇴': 'Delete account', '계정과 작성한 콘텐츠를 영구 삭제합니다': 'Permanently delete your account and content', '탈퇴': 'Delete', '탈퇴하면 복구할 수 없습니다': 'Account deletion cannot be undone', '현재 익명 계정으로 다시 접속할 수 없으며, 새로운 계정에는 기존 정보와 포인트가 이전되지 않습니다.': 'You cannot access this anonymous account again, and its data and points cannot be transferred.', '삭제되는 정보': 'Data that will be deleted', '• 프로필, 사진 및 위치': '• Profile, photos, and location', '• 톡쓰기, 게시글, 댓글 및 첨부 사진': '• Talk cards, posts, comments, and attachments', '• 대화 신청, 채팅방 및 메시지': '• Chat requests, chat rooms, and messages', '• 포인트, 출석과 활동 보상 내역': '• Points, check-ins, and activity rewards', '• 차단 정보, 알림과 기기 푸시 토큰': '• Blocks, notifications, and device push tokens', '계정과 데이터 영구 삭제': 'Permanently delete account and data',
  '포인트 충전': 'Add points', '필요한 만큼 충전하세요': 'Add the points you need', '구매한 포인트는 대화 신청과 프로필 정보 수정에 사용할 수 있어요': 'Use purchased points for chat requests and profile updates.', '결제 상품을 확인하고 있어요': 'Loading purchase options', '결제 중…': 'Purchasing…', '포인트 내역': 'Point history', '아직 포인트 내역이 없습니다.': 'No point activity yet.', '내역을 불러오고 있어요.': 'Loading point history.', '포인트 상세': 'Point details', '현재 포인트': 'Current points', '충전하기': 'Add points', '포인트 내역 보기': 'View point history', '적립 및 사용 내역을 확인해요': 'Review points earned and spent.',
  '최초 지급': 'Welcome grant', '출석체크': 'Daily check-in', '톡쓰기 등록': 'Talk card reward', '익명 게시글 작성': 'Anonymous post reward', '익명 댓글 작성': 'Anonymous comment reward', '프로필 정보 수정': 'Profile update', '포인트 구매 환불': 'Point purchase refund', '운영자 포인트 조정': 'Admin adjustment', '포인트 변경': 'Point adjustment',
  '내 프로필': 'My Profile', '프로필 수정': 'Edit profile', '프로필 사진': 'Profile photo', '사진 변경은 무료예요': 'Photo changes are free.', '사진 선택': 'Choose photo', '사진 업데이트': 'Update photo', '사진 저장 중…': 'Saving photo…', '기본 정보': 'Basic information', '최대 5개': 'Up to 5', '기본 정보 수정 · 100P': 'Update profile · 100P', '수정 중…': 'Updating…',
  '대화 카드 만들기': 'Create talk card', '대화 카드 수정': 'Edit talk card', '하고 싶은 이야기를 먼저 알려주세요.': 'Tell people what you would like to talk about.', '내용을 수정하면 카드가 최신 글로 갱신돼요.': 'Editing refreshes the card as a new post.', '대화 목적': 'Conversation goal', '어떤 이야기를 나누고 싶나요?': 'What would you like to talk about?', '예: 이번 주말 전시 같이 볼 사람 있나요?': 'Example: Anyone want to visit an exhibition this weekend?', '좋은 대화를 위한 약속': 'Guidelines for good conversations', '개인 연락처, 선정적인 표현, 만남 강요는 작성할 수 없어요.': 'Do not post personal contact details, sexual content, or pressure others to meet.', '대화 카드 등록': 'Publish talk card', '등록 중…': 'Publishing…', '수정 완료': 'Save changes',
  '내 대화 카드': 'My talk cards', '등록된 내 대화 카드가 없어요.': 'You have no active talk cards.', '아직 표시할 대화 카드가 없어요.': 'No talk cards to show yet.',
  '고객센터 문의': 'Customer Support', '이용 중 궁금한 점을 운영자에게 문의하세요': 'Ask our team for help with the service.', '문의하기': 'Contact us', '운영시간과 문의량에 따라 답변이 늦어질 수 있어요. 긴급한 위험은 관계 기관에 바로 연락해 주세요.': 'Replies may take time depending on support hours and volume. Contact local emergency services for urgent danger.', '무엇을 도와드릴까요?': 'How can we help?', '문의 내용을 보내면 운영자가 이곳으로 답변해 드립니다': 'Send a message and our team will reply here.', '문의 내용을 입력하세요': 'Describe your question',
  '이용약관 및 개인정보': 'Terms & Privacy', '서비스 이용약관과 개인정보처리방침을 확인해요': 'Review the Terms of Service and Privacy Policy.', '약관 및 개인정보': 'Terms & Privacy', '이용약관': 'Terms of Service', '개인정보처리방침': 'Privacy Policy',
  '새 글': 'New post', '글쓰기': 'Write', '게시글 작성': 'Create post', '제목': 'Title', '내용': 'Content', '댓글': 'Comments', '답글': 'Replies', '좋아요': 'Like', '싫어요': 'Dislike', '신고': 'Report', '차단': 'Block', '차단 해제': 'Unblock', '대화신청': 'Chat request', '내 발견 목록에서만 숨기기': 'Hide only from my Discover', '서로의 카드와 신청 숨기기': 'Hide cards and requests from each other', '이 카드를 삭제할까요?': 'Remove this card?', '상대방의 글은 삭제되지 않고 내 발견 목록에서만 보이지 않게 됩니다.': 'The other person’s post will not be deleted. It will only be hidden from your Discover list.',
  '익명 게시판': 'Anonymous Board', '익명으로 편하게 이야기를 나눠요': 'Share freely and anonymously.', '검색': 'Search', '인기': 'Popular', '남': 'Men', '여': 'Women', '제목, 내용, 작성자 검색': 'Search title, content, or author', '검색 닫기': 'Close search', '제목을 입력하세요.': 'Enter a title', '자유롭게 이야기를 남겨주세요.': 'Share what is on your mind.', '사진 (선택)': 'Photo (optional)', '사진 삭제': 'Remove photo', '사진 첨부': 'Attach photo', '등록': 'Publish', '첫 댓글을 남겨보세요.': 'Be the first to comment.', '댓글을 입력하세요': 'Write a comment', '삭제된 댓글에 답글': 'Reply to deleted comment', '익명 글쓰기': 'Create anonymous post', '편하게 대화를 시작해 보세요.': 'Start a friendly conversation.',
  '받은 요청': 'Received', '보낸 요청': 'Sent', '채팅방': 'Chat rooms', '수락': 'Accept', '거절': 'Decline', '요청 취소': 'Cancel request', '메시지를 입력하세요': 'Type a message', '사진 보내기': 'Send photo',
  '음란물·성적 콘텐츠': 'Sexual content', '불법 만남·성매매 유도': 'Illegal meetings or solicitation', '욕설·괴롭힘': 'Abuse or harassment', '사기·금전 요구': 'Fraud or requests for money', '광고·도배': 'Spam or advertising', '개인정보 노출': 'Exposed personal information', '미성년자 의심': 'Suspected minor', '불법 촬영물 의심': 'Suspected illegal imagery', '두 손가락으로 확대 · 한 손가락으로 이동 · 두 번 탭으로 초기화': 'Pinch to zoom · drag to move · double-tap to reset', '익명 이용자': 'Anonymous user', '익명게시판 닉네임': 'Board alias', '요청 중…': 'Sending request…', '대화 요청하기 · 100P': 'Send chat request · 100P', '대화 신청': 'Chat request', '첫 인사를 함께 보내주세요': 'Include a short introduction', '예: 저도 전시를 좋아해요. 편하게 이야기해 볼까요?': 'Example: I like exhibitions too. Want to chat?', '첫 메시지를 보내 대화를 시작해 보세요.': 'Send the first message to start chatting.', '메시지 보내기': 'Send a message', '사진 첨부됨': 'Photo attached', '메시지를 함께 적거나 바로 전송할 수 있어요': 'Add a message or send it now.', '대화 관리': 'Manage chat', '대화 상대 신고': 'Report user', '신고 사유를 선택해 주세요. 운영자가 최근 대화 내용과 함께 검토합니다.': 'Choose a reason. Our team will review it with recent messages.', '상세 내용': 'Details', '(선택)': '(optional)', '운영자가 확인해야 할 내용을 적어주세요': 'Add details for our review', '허위 신고는 서비스 이용이 제한될 수 있으며, 신고 사실은 상대방에게 공개되지 않습니다.': 'False reports may result in restrictions. The report is not disclosed to the other person.', '접수 중…': 'Submitting…', '신고 접수': 'Submit report', '차단 친구 관리': 'Blocked users', '내가 차단한 친구만 표시됩니다. 차단을 해제하면 서로의 공개 활동과 대화 신청이 다시 허용됩니다.': 'Only users you blocked appear here. Unblocking restores public visibility and chat requests.', '차단한 친구가 없어요': 'No blocked users', '차단한 친구가 생기면 이곳에서 관리할 수 있습니다.': 'People you block will appear here.',
  '새로고침': 'Refresh', '다시 시도해 주세요.': 'Please try again.', '처리 중…': 'Processing…', '완료': 'Done', '확인': 'OK', '(VAT 포함)': '(VAT included)',
  '아직 주변에 등록된 대화 카드가 없어요.': 'No nearby talk cards yet.', '화면을 아래로 당겨 새로고침해 보세요.': 'Pull down to refresh.', '⌕ 검색': '⌕ Search',
  '위치, 사진, 알림 등 기기 권한 관리 · ': 'Manage location, photo, and notification permissions · ', ' 허용': ' allowed',
  '사진 접근 권한이 필요해요': 'Photo permission required', '사진 권한이 필요해요': 'Photo permission required', '사진을 선택하지 못했어요': 'Could not select photo', '사진이 너무 커요': 'Photo is too large', '8MB 이하의 사진을 선택해 주세요.': 'Choose a photo smaller than 8 MB.', '메시지를 불러오지 못했어요': 'Could not load messages', '전송 실패': 'Send failed', '삭제하지 못했어요': 'Could not delete', '차단하지 못했어요': 'Could not block', '차단 완료': 'Blocked', '대화방 삭제 완료': 'Chat deleted', '신고하지 못했어요': 'Could not submit report', '신고가 접수되었습니다': 'Report submitted', '나중에': 'Later',
  '신청할 수 없는 글': 'Chat unavailable', '데모 글에는 대화를 신청할 수 없어요. 발견 목록을 새로고침해 실제 사용자의 글을 선택해 주세요.': 'Chat requests are unavailable for demo posts. Refresh Discover and choose a real user post.', '대화 요청 완료': 'Chat request sent', '상대방의 수락을 기다리고 있습니다.': 'Waiting for the other person to accept.', '신청하지 못했어요': 'Could not send request', '이미 이 카드에 대화를 신청했어요.': 'You already requested a chat for this card.', '포인트가 부족해요. 대화를 신청하려면 100P가 필요합니다.': 'You need 100P to request a chat.', '만료되었거나 사용할 수 없는 대화 카드예요.': 'This talk card has expired or is unavailable.', '차단 관계에서는 대화를 신청할 수 없어요.': 'Chat requests are unavailable between blocked users.',
  '게시판을 불러오지 못했어요': 'Could not load the board', '댓글을 불러오지 못했어요': 'Could not load comments', '댓글을 등록하지 못했어요': 'Could not post comment', '댓글을 삭제할까요?': 'Delete this comment?', '삭제한 댓글은 복구할 수 없습니다.': 'Deleted comments cannot be restored.', '게시글을 삭제할까요?': 'Delete this post?', '게시글과 댓글이 모두 삭제됩니다.': 'The post and all comments will be deleted.', '좋아요를 반영하지 못했어요': 'Could not update like', '싫어요를 반영하지 못했어요': 'Could not update dislike', '글을 등록하지 못했어요': 'Could not publish post', '신고하기': 'Report', '신고 사유 선택': 'Choose a report reason', '부적절한 내용': 'Inappropriate content', '원하는 기능을 선택해 주세요.': 'Choose an action.',
  '회원 탈퇴 완료': 'Account deleted', '계정과 서비스 데이터가 삭제되었습니다.': 'Your account and service data were deleted.', '회원 탈퇴 실패': 'Could not delete account', '탈퇴합니다': 'DELETE', '신고 처리와 서비스 악용 방지를 위해 보존이 필요한 최소 운영 기록은 이용자 식별정보와 작성 내용을 제거한 후 제한적으로 남을 수 있습니다.': 'Minimum operational records required for reports and abuse prevention may remain after identifiers and authored content are removed.',
  '결제가 완료됐어요': 'Purchase completed', '스토어 확인 후 포인트가 자동으로 충전됩니다. 잠시만 기다려 주세요.': 'Points will be added automatically after store verification.', '결제하지 못했어요': 'Purchase failed', '결제는 iPhone 또는 Android 앱에서 이용할 수 있어요.': 'Purchases are available in the iPhone or Android app.', '결제 서비스 키가 아직 등록되지 않았어요.': 'The payment service key is not configured.', '서버 연결 후 결제를 이용할 수 있어요.': 'Purchases are available after connecting to the server.', '스토어에 등록된 포인트 상품을 찾지 못했어요.': 'No point products were found in the store.', '결제 상품을 불러오지 못했어요. 잠시 후 다시 시도해 주세요.': 'Could not load purchase options. Please try again later.', '결제는 Apple App Store 또는 Google Play에서 처리됩니다. 실제 청구 금액은 결제 확인 화면의 현지 통화 가격을 기준으로 합니다.': 'Payments are processed through the Apple App Store or Google Play. The actual amount charged is based on the local-currency price shown on the purchase confirmation screen.',
  '아직 작성한 대화 카드가 없어요.': 'You have not created a talk card yet.', '내 위치': 'My location', '믿을 수 있는 대화자': 'Trusted user', '내 글을 삭제할까요?': 'Delete your post?', '삭제하면 다른 사용자의 발견 목록에서 즉시 사라집니다.': 'It will immediately disappear from Discover.', '내 글이 발견 목록에서 삭제되었습니다.': 'Your post was removed from Discover.', '글을 작성해 주세요': 'Write something first', '남기고 싶은 말을 공백을 제외하고 1자 이상 입력해 주세요.': 'Enter at least one non-space character.', '데모 대화 카드가 등록되었어요.': 'Demo talk card published.', '작성 또는 수정한 시점부터 30일 동안 발견 목록에 표시됩니다.': 'It will appear in Discover for 30 days.', '등록 실패': 'Publish failed', '남기고 싶은 말은 1~120자로 입력해 주세요.': 'Enter between 1 and 120 characters.',
  '출석 확인 중…': 'Checking in…', '출석 상태 확인 중…': 'Checking status…', '출석체크 · +50P': 'Daily check-in · +50P', '출석체크 완료 · 24시간 후 가능': 'Checked in · Available again in 24 hours', '출석체크 실패': 'Check-in failed', '출석체크 완료': 'Check-in complete', '이미 출석했어요': 'Already checked in', '출석체크 보상 50P가 충전되었습니다.': 'Your 50P check-in reward was added.', '마지막 출석체크 후 24시간이 지나면 다시 받을 수 있어요.': 'You can claim it again after 24 hours.',
  '사진 변경 완료': 'Photo updated', '프로필 사진을 무료로 변경했습니다.': 'Your profile photo was updated for free.', '사진 변경 실패': 'Photo update failed', '프로필 수정 완료': 'Profile updated', '프로필 정보를 수정했습니다.': 'Your profile was updated.', '프로필 수정 실패': 'Profile update failed', '포인트가 부족합니다. 프로필 정보를 수정하려면 100P가 필요해요.': 'You need 100P to update profile details.', '닉네임, 나이, 성별을 한 번 수정할 때 100P가 사용돼요': 'Updating nickname, age, and gender costs 100P.',
  '채팅': 'Chats', '받은 신청': 'Received', '보낸 신청': 'Sent', '서로 수락한 뒤 안전하게 이야기해요': 'Chat safely after both people agree.', '대기 중': 'Pending', '수락됨': 'Accepted', '거절됨': 'Declined', '취소됨': 'Cancelled', '대화를 시작해 보세요.': 'Start a conversation.', '아직 열린 채팅방이 없어요.\n대화 신청이 수락되면 여기에 표시됩니다.': 'No open chats yet.\nAccepted requests appear here.', '받은 대화 신청이 없어요.': 'No received chat requests.', '보낸 대화 신청이 없어요.': 'No sent chat requests.', '삭제 중…': 'Deleting…', '채팅방 열기': 'Open chat', '대화방을 삭제할까요?': 'Delete this chat?', '상대방의 대화 목록에서도 함께 삭제됩니다.': 'It will also be removed from the other person’s chat list.', '상대방을 차단할까요?': 'Block this person?', '이 대화방이 삭제되고 상대방은 더 이상 대화를 신청하거나 메시지를 보낼 수 없습니다.': 'This chat will be deleted and the person can no longer request chats or send messages.', '차단을 해제할까요?': 'Unblock this person?', '차단 목록을 불러오지 못했어요': 'Could not load blocked users', '차단을 해제하지 못했어요': 'Could not unblock user',
}

const replacements: Array<[RegExp, string]> = [
  [/남(\d+)세/g, 'M $1'], [/여(\d+)세/g, 'F $1'], [/기타(\d+)세/g, 'O $1'],
  [/남(?=\d)/g, 'M '], [/여(?=\d)/g, 'F '], [/기타(?=\d)/g, 'O '],
  [/(\d+)대 초반/g, 'Early $1s'], [/(\d+)대 중반/g, 'Mid $1s'], [/(\d+)대 후반/g, 'Late $1s'], [/(\d+)대/g, '$1s'],
  [/(\d+)분 전/g, '$1m ago'], [/(\d+)시간 전/g, '$1h ago'], [/(\d+)일 전/g, '$1d ago'], [/(\d+)세/g, 'Age $1'],
  [/(\d+)분전/g, '$1m ago'], [/(\d+)시간전/g, '$1h ago'], [/(\d+)일전/g, '$1d ago'],
  [/좋아요 (\d+)/g, 'Like $1'], [/싫어요 (\d+)/g, 'Dislike $1'], [/댓글 (\d+)/g, 'Comment $1'],
  [/(.+)님에게 답글 작성 중/g, 'Replying to $1'], [/(.+)님에게 답글/g, 'Reply to $1'], [/(.+)님에게/g, 'To $1'], [/(.+)님을 신고합니다/g, 'Report $1'],
  [/(.+)님과의 대화를 관리합니다/g, 'Manage your chat with $1'], [/게시판 ·/g, 'Board ·'], [/ 차단$/g, ' blocked'],
  [/최소 (\d+)자/g, 'Minimum $1 character'], [/남은 포인트:/g, 'Points remaining:'], [/명/g, ' people'],
  [/등록 완료/g, 'Published'], [/삭제 완료/g, 'Deleted'], [/저장 완료/g, 'Saved'], [/실패/g, ' failed'], [/오류/g, ' error'],
]

export function localizeText(value: string) {
  const brandName = activeLanguage === 'ko' ? '잉톡' : 'Ingtalk'
  if (value === '잉톡') return brandName
  if (activeLanguage === 'ko' || !/[가-힣]/.test(value)) return value
  const direct = exact[value]
  if (direct) return direct.replaceAll('IngTalk', brandName)
  const boardAlias = boardAliasDisplayName(value, activeLanguage)
  if (boardAlias !== value) return boardAlias
  let translated = value
  for (const [pattern, replacement] of replacements) translated = translated.replace(pattern, replacement)
  return exact[translated] ?? translated
}

function localizeNode(node: ReactNode): ReactNode {
  if (typeof node === 'string') return localizeText(node)
  if (Array.isArray(node)) return Children.map(node, localizeNode)
  if (isValidElement(node)) {
    const element = node as ReactElement<{ children?: ReactNode }>
    if (element.props.children !== undefined) return cloneElement(element, undefined, localizeNode(element.props.children))
  }
  return node
}

type LocalizedTextProps = TextProps & { localize?: boolean }

export const Text = forwardRef<NativeText, LocalizedTextProps>(function LocalizedText({ children, localize = true, ...props }, ref) {
  return <NativeText ref={ref} {...props}>{localize ? localizeNode(children) : children}</NativeText>
})

export const TextInput = forwardRef<NativeTextInput, TextInputProps>(function LocalizedTextInput(props, ref) {
  return <NativeTextInput ref={ref} {...props} placeholder={props.placeholder ? localizeText(props.placeholder) : undefined} />
})

export type TextInput = NativeTextInput
