<%@ Language="VBScript" CodePage="65001" %>
<%
Response.CharSet = "utf-8"
Dim requestedLang, lang
requestedLang = LCase(Trim(Request.QueryString("lang")))
If requestedLang = "ko" Or requestedLang = "en" Then
  lang = requestedLang
  Response.Cookies("ingtalk_site_lang") = lang
  Response.Cookies("ingtalk_site_lang").Expires = DateAdd("yyyy", 1, Now())
  Response.Cookies("ingtalk_site_lang").Secure = True
Else
  lang = LCase(Trim(Request.Cookies("ingtalk_site_lang")))
  If lang <> "ko" And lang <> "en" Then lang = "ko"
End If
%><!doctype html>
<html lang="<%=lang%>"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><% If lang="en" Then %><title>Ingtalk Child Safety Standards</title><meta name="description" content="Ingtalk standards against child sexual abuse and exploitation"><% Else %><title>잉톡 아동 안전 표준</title><meta name="description" content="잉톡의 아동 성적 학대 및 착취 방지 기준"><% End If %><link rel="stylesheet" href="../styles.css"></head>
<body><a class="skip" href="#main"><% If lang="en" Then %>Skip to content<% Else %>본문으로 바로가기<% End If %></a>
<header class="site-header"><div class="header-inner"><a class="brand" href="../index.asp?lang=<%=lang%>"><% If lang="en" Then %>Ingtalk<% Else %>잉톡<% End If %></a><div class="header-actions"><nav class="nav" aria-label="<% If lang="en" Then %>Main navigation<% Else %>주요 메뉴<% End If %>"><a href="../terms.asp?lang=<%=lang%>"><% If lang="en" Then %>Terms<% Else %>이용약관<% End If %></a><a href="../privacy.asp?lang=<%=lang%>"><% If lang="en" Then %>Privacy<% Else %>개인정보<% End If %></a><a href="../community.asp?lang=<%=lang%>"><% If lang="en" Then %>Community<% Else %>운영정책<% End If %></a><a aria-current="page" href="?lang=<%=lang%>"><% If lang="en" Then %>Child safety<% Else %>아동 안전<% End If %></a><a href="../support.asp?lang=<%=lang%>"><% If lang="en" Then %>Support<% Else %>고객지원<% End If %></a></nav><nav class="language-switch" aria-label="Language"><a <% If lang="ko" Then Response.Write("aria-current=""true""") %> href="?lang=ko" lang="ko">한국어</a><span aria-hidden="true">|</span><a <% If lang="en" Then Response.Write("aria-current=""true""") %> href="?lang=en" lang="en">English</a></nav></div></div></header>
<main id="main" class="container"><% If lang="en" Then %>
<header class="page-head"><h1>Child Safety Standards</h1><p class="effective">Ingtalk · Published by Itembus · Effective August 23, 2026</p></header>
<div class="notice danger"><strong>Zero tolerance for child sexual abuse and exploitation</strong><p>Ingtalk prohibits child sexual abuse and exploitation (CSAE) and child sexual abuse material (CSAM) in every part of the service. Ingtalk is intended only for users age 19 or older.</p></div>
<h2>1. Prohibited conduct and content</h2><p>Users must not create, upload, request, possess, distribute, link to, promote, or facilitate:</p><ul><li>CSAM, including real, altered, generated, or illustrated sexual depictions involving a minor;</li><li>grooming, sexual solicitation of a minor, sextortion, or attempts to move a minor to another service for sexual purposes;</li><li>child sex trafficking or any commercial sexual exploitation of a child;</li><li>instructions, links, coded language, or communities intended to obtain or exchange CSAE content; or</li><li>threats, coercion, blackmail, or disclosure of a child's personal information that may place a child at risk.</li></ul>
<h2>2. Reporting in Ingtalk</h2><p>Users can use the report controls available in the app on profiles, conversation cards, board content, and chats. Select the child-safety or suspected-minor reason where available and provide only the information needed for review. Reports are restricted to authorized operators and the reporter is not identified to the reported user.</p><p>If an in-app report cannot be used, contact <a href="mailto:itembus@itembus.com?subject=Ingtalk%20child%20safety%20report">itembus@itembus.com</a>. Do not download, forward, or attach suspected CSAM. Provide a content or account identifier and the approximate time instead.</p>
<h2>3. Review and enforcement</h2><p>Itembus reviews child-safety reports as a priority. When we obtain actual knowledge of prohibited content or conduct, we may restrict access, remove content, suspend or permanently terminate accounts, preserve information where legally permitted and necessary, and prevent repeat abuse. We do not notify an alleged offender in a way that could increase danger or interfere with a lawful investigation.</p>
<h2>4. Cooperation and reporting to authorities</h2><p>Ingtalk complies with applicable child-safety laws. Confirmed CSAM and credible child-exploitation threats are reported to the National Center for Missing &amp; Exploited Children (NCMEC) or another competent regional or national authority when required by applicable law. We respond to valid legal requests and preserve relevant records for the period required by law or a legitimate safety investigation.</p>
<h2>5. Privacy and retention</h2><p>Child-safety reports and enforcement evidence are accessible only to authorized personnel and are used for safety, legal compliance, investigations, and appeals. They are retained only as described in the <a href="../privacy.asp?lang=en">Privacy Policy</a> or as required by law, then securely deleted.</p>
<h2>6. Immediate danger</h2><p>If a child may be in immediate danger, contact local emergency services or law enforcement immediately. Do not wait for an Ingtalk response.</p>
<h2>7. Child-safety contact</h2><ul class="contact-list"><li>Service: Ingtalk</li><li>Developer and operator: Itembus</li><li>Designated contact: Yongil Cho, Representative</li><li>Email: <a href="mailto:itembus@itembus.com?subject=Ingtalk%20child%20safety">itembus@itembus.com</a></li><li>Phone: <a href="tel:15551645">1555-1645</a></li><li>Address: 2F, Suite 215, 4236 Donghae-daero, Sokcho-si, Gangwon State, Republic of Korea</li></ul>
<p>Related policies: <a href="../community.asp?lang=en">Community Guidelines</a>, <a href="../terms.asp?lang=en">Terms of Service</a>, and <a href="../privacy.asp?lang=en">Privacy Policy</a>.</p>
<% Else %>
<header class="page-head"><h1>아동 안전 표준</h1><p class="effective">잉톡 · 게시자 아이템버스 · 시행일 2026년 8월 23일</p></header>
<div class="notice danger"><strong>아동 성적 학대 및 착취 무관용 원칙</strong><p>잉톡은 서비스의 모든 영역에서 아동 성적 학대 및 착취(CSAE)와 아동 성적 학대물(CSAM)을 금지합니다. 잉톡은 만 19세 이상만 이용할 수 있습니다.</p></div>
<h2>1. 금지되는 행위와 콘텐츠</h2><p>이용자는 다음 콘텐츠나 행위를 제작, 업로드, 요청, 소지, 배포, 연결, 홍보 또는 조장해서는 안 됩니다.</p><ul><li>미성년자가 포함된 실제·변형·생성·삽화 형태의 성적 묘사를 포함한 CSAM</li><li>미성년자 대상 그루밍, 성적 접근, 성착취 목적의 외부 서비스 이동 유도 또는 성적 협박</li><li>아동 성매매·인신매매 등 아동에 대한 상업적 성착취</li><li>아동 성착취 콘텐츠를 획득·교환하기 위한 지침, 링크, 은어 또는 모임</li><li>아동을 위험에 빠뜨릴 수 있는 위협, 강요, 협박 또는 개인정보 공개</li></ul>
<h2>2. 잉톡 앱에서 신고하기</h2><p>이용자는 앱의 프로필, 대화 카드, 게시판 콘텐츠 및 대화에 제공되는 신고 기능을 사용할 수 있습니다. 가능한 경우 아동 안전 또는 미성년자 의심 사유를 선택하고 검토에 필요한 최소 정보만 제공해 주세요. 신고 내용은 권한 있는 운영자만 확인하며 신고자의 신원은 신고 대상에게 공개하지 않습니다.</p><p>앱 내 신고를 사용할 수 없는 경우 <a href="mailto:itembus@itembus.com?subject=%EC%9E%89%ED%86%A1%20%EC%95%84%EB%8F%99%20%EC%95%88%EC%A0%84%20%EC%8B%A0%EA%B3%A0">itembus@itembus.com</a>으로 알려주세요. 의심되는 CSAM을 내려받거나 전달하거나 이메일에 첨부하지 말고, 콘텐츠·계정 식별정보와 대략적인 발생 시각만 알려주세요.</p>
<h2>3. 검토와 운영 조치</h2><p>아이템버스는 아동 안전 신고를 우선적으로 검토합니다. 금지 콘텐츠나 행위를 실제로 인지하면 접근 제한, 콘텐츠 삭제, 계정 일시 정지 또는 영구 정지, 법적으로 허용되고 필요한 범위의 정보 보존 및 반복 악용 방지 조치를 할 수 있습니다. 아동의 위험을 키우거나 적법한 수사를 방해할 수 있는 방식으로 위반 의심자에게 알리지 않습니다.</p>
<h2>4. 관계 기관 신고 및 협조</h2><p>잉톡은 적용되는 아동 안전 법규를 준수합니다. 확인된 CSAM과 신빙성 있는 아동 성착취 위험은 적용 법률이 요구하는 경우 미국 실종학대아동방지센터(NCMEC) 또는 관할 지역·국가 기관에 신고합니다. 적법한 요청에 협조하며 관련 기록은 법률 또는 정당한 안전 조사에서 요구되는 기간 동안 보존합니다.</p>
<h2>5. 개인정보와 보유기간</h2><p>아동 안전 신고와 운영 조치 증거는 권한 있는 담당자만 접근하며 안전 운영, 법적 의무, 조사 및 이의제기에만 사용합니다. <a href="../privacy.asp?lang=ko">개인정보처리방침</a> 또는 법률에서 정한 기간까지만 보유한 후 안전하게 삭제합니다.</p>
<h2>6. 긴급한 위험</h2><p>아동이 즉각적인 위험에 처했다고 판단되면 잉톡의 답변을 기다리지 말고 경찰 112 등 지역 긴급 구조기관이나 수사기관에 즉시 신고하세요.</p>
<h2>7. 아동 안전 담당 연락처</h2><ul class="contact-list"><li>서비스명: 잉톡(Ingtalk)</li><li>개발·운영자: 아이템버스(Itembus)</li><li>지정 담당자: 대표자 조용일</li><li>이메일: <a href="mailto:itembus@itembus.com?subject=%EC%9E%89%ED%86%A1%20%EC%95%84%EB%8F%99%20%EC%95%88%EC%A0%84">itembus@itembus.com</a></li><li>전화: <a href="tel:15551645">1555-1645</a></li><li>주소: 강원특별자치도 속초시 동해대로 4236, 2층 215호</li></ul>
<p>관련 정책: <a href="../community.asp?lang=ko">커뮤니티 운영정책</a>, <a href="../terms.asp?lang=ko">이용약관</a>, <a href="../privacy.asp?lang=ko">개인정보처리방침</a></p>
<% End If %></main>
<footer class="site-footer"><div class="footer-inner"><div class="footer-links"><a href="../terms.asp?lang=<%=lang%>"><% If lang="en" Then %>Terms of Service<% Else %>이용약관<% End If %></a><a href="../privacy.asp?lang=<%=lang%>"><% If lang="en" Then %>Privacy Policy<% Else %>개인정보처리방침<% End If %></a><a href="../deletion.asp?lang=<%=lang%>"><% If lang="en" Then %>Account deletion<% Else %>계정 삭제<% End If %></a><a href="?lang=<%=lang%>"><% If lang="en" Then %>Child safety<% Else %>아동 안전<% End If %></a><a href="../support.asp?lang=<%=lang%>"><% If lang="en" Then %>Support<% Else %>고객지원<% End If %></a></div><div><% If lang="en" Then %>Itembus · Representative: Yongil Cho · 2F, Suite 215, 4236 Donghae-daero, Sokcho-si, Gangwon State, Republic of Korea<br>Support: 1555-1645 · itembus@itembus.com<% Else %>아이템버스 · 대표자 조용일 · 강원특별자치도 속초시 동해대로 4236, 2층 215호<br>고객지원 1555-1645 · itembus@itembus.com<% End If %></div></div></footer></body></html>
