<%@ Language="VBScript" CodePage="65001" %><% Response.CharSet="utf-8": pageTitleKo="잉톡 계정 및 데이터 삭제": pageTitleEn="Delete Your Ingtalk Account and Data": pageDescriptionKo="잉톡 계정과 관련 데이터 삭제 요청 방법": pageDescriptionEn="How to delete an Ingtalk account or request deletion of associated data": currentPage="deletion": currentFile="deletion.asp" %><!--#include file="_header.asp"-->
<main id="main" class="container"><% If lang="en" Then %>
<header class="page-head"><h1>Account &amp; Data Deletion</h1><p class="effective">How to delete an Ingtalk account and associated data.</p></header>
<h2>Delete immediately in the app</h2><ol><li>Open the Ingtalk app.</li><li>Go to <strong>My Info</strong> in the bottom menu.</li><li>Select <strong>Delete account</strong>.</li><li>Enter the confirmation phrase and select <strong>Permanently delete account and data</strong>.</li></ol><div class="notice danger"><strong>Account deletion cannot be undone.</strong><p>Your profile, content, and user-accessible chats cannot be restored after deletion.</p></div>
<h2>If you cannot use the app</h2><p>You can submit an external deletion request by email. To prevent deletion by another person, we may ask for additional details about prior app use.</p><div class="button-row"><a class="button" href="mailto:itembus@itembus.com?subject=Ingtalk%20account%20deletion%20request">Request account deletion</a><a class="button secondary" href="<%=LangUrl("support.asp")%>">Support information</a></div><div class="notice"><strong>Include in your email</strong><ul><li>Subject: Ingtalk account deletion request</li><li>Your nickname in the app</li><li>Approximate date of last use</li><li>An email address where we can respond</li></ul><p>Do not attach chat contents, passwords, or identity-document photos.</p></div>
<p>Deletion applies to the entire Ingtalk account shared by linked phone, Google and Kakao sign-ins and all registered devices. It cannot be undone. Support verifies account ownership before processing an external request; a nickname alone is not proof of ownership. Do not send passwords or SMS verification codes by email.</p>
<h2>Data deleted with the account</h2><ul><li>Profile, profile photo, and location</li><li>Talk cards, posts, comments, and attached photos</li><li>Chat requests, user-accessible chat rooms, and messages</li><li>Points, check-ins, activity rewards, blocks, and push tokens</li></ul>
<h2>Delete selected data while keeping the account</h2><p>You may request deletion of some or all data you provided without deleting your account.</p><div class="button-row"><a class="button" href="mailto:itembus@itembus.com?subject=Ingtalk%20partial%20data%20deletion%20request">Request data deletion</a></div><div class="notice"><strong>Data you may request to delete</strong><ul><li>Profile or profile photo</li><li>Talk cards, posts, or comments</li><li>Chat requests, chat rooms, or messages</li><li>Location or push-notification token</li></ul><p>Include your nickname, approximate last-use date, and the data to delete. We may request additional verification to protect your account and other users.</p></div>
<h2>Data retained for limited periods</h2><div class="table-wrap"><table><thead><tr><th>Data</th><th>Retention</th><th>Purpose</th></tr></thead><tbody><tr><td>Report and enforcement evidence and safety message backups</td><td>Up to one year after creation or last handling</td><td>Safety, disputes, and lawful requests</td></tr><tr><td>Device-wallet and repeat-registration prevention records</td><td>Up to one year after last use or withdrawal</td><td>Prevent duplicate rewards and abuse</td></tr><tr><td>Legally required records</td><td>Period required by law</td><td>Legal compliance</td></tr></tbody></table></div><p>Retained records are deleted irreversibly when the retention purpose ends.</p><h2>Contact</h2><p>Email: <a href="mailto:itembus@itembus.com">itembus@itembus.com</a> / Phone: <a href="tel:15551645">1555-1645</a></p>
<% Else %>
<header class="page-head"><h1>계정 및 데이터 삭제</h1><p class="effective">잉톡 계정과 관련 데이터의 삭제를 요청하는 방법입니다.</p></header>
<h2>앱에서 즉시 삭제하기</h2><ol><li>잉톡 앱을 실행합니다.</li><li>하단의 <strong>내 정보</strong>로 이동합니다.</li><li><strong>회원 탈퇴</strong>를 선택합니다.</li><li>확인 문구를 입력하고 <strong>계정과 데이터 영구 삭제</strong>를 누릅니다.</li></ol><div class="notice danger"><strong>회원 탈퇴는 되돌릴 수 없습니다.</strong><p>탈퇴 후 프로필, 콘텐츠와 이용자에게 표시되던 대화는 복구되지 않습니다.</p></div>
<h2>앱을 사용할 수 없는 경우</h2><p>고객지원 이메일로 외부 삭제 요청을 접수할 수 있습니다. 타인에 의한 삭제를 방지하기 위해 앱 이용 정보 등을 통한 추가 확인을 요청할 수 있습니다.</p><div class="button-row"><a class="button" href="mailto:itembus@itembus.com?subject=%EC%9E%89%ED%86%A1%20%EA%B3%84%EC%A0%95%20%EC%82%AD%EC%A0%9C%20%EC%9A%94%EC%B2%AD">계정 삭제 요청</a><a class="button secondary" href="<%=LangUrl("support.asp")%>">고객지원 안내</a></div><div class="notice"><strong>이메일 작성 내용</strong><ul><li>제목: 잉톡 계정 삭제 요청</li><li>앱에서 사용한 닉네임</li><li>마지막으로 이용한 대략적인 날짜</li><li>회신받을 이메일 주소</li></ul><p>채팅 내용, 비밀번호, 신분증 사진은 첨부하지 마세요.</p></div>
<p>탈퇴는 연결된 휴대폰·Google·카카오 로그인 수단과 모든 등록 기기가 공유하는 잉톡 계정 전체에 적용됩니다. 연결된 로그인 수단으로 삭제된 계정이나 포인트를 되살릴 수 없습니다. 외부 요청에서는 계정 소유 확인 후 처리하며 닉네임만으로 다른 사람의 계정을 삭제하지 않습니다.</p><h2>계정과 함께 삭제되는 정보</h2><ul><li>프로필, 프로필 사진과 위치</li><li>대화 카드, 게시글, 댓글과 첨부 사진</li><li>대화 신청, 이용자에게 표시되는 채팅방과 메시지</li><li>포인트, 출석·활동 보상, 차단 정보와 푸시 토큰</li></ul>
<h2>계정을 유지하고 일부 데이터만 삭제하기</h2><p>계정을 삭제하지 않고도 본인이 제공한 데이터의 일부 또는 전체 삭제를 요청할 수 있습니다.</p><div class="button-row"><a class="button" href="mailto:itembus@itembus.com?subject=%EC%9E%89%ED%86%A1%20%EC%9D%BC%EB%B6%80%20%EB%8D%B0%EC%9D%B4%ED%84%B0%20%EC%82%AD%EC%A0%9C%20%EC%9A%94%EC%B2%AD">일부 데이터 삭제 요청</a></div><div class="notice"><strong>요청할 수 있는 데이터</strong><ul><li>프로필 또는 프로필 사진</li><li>대화 카드, 게시글 또는 댓글</li><li>대화 신청, 채팅방 또는 메시지</li><li>위치 또는 푸시 알림 토큰</li></ul><p>닉네임, 마지막 이용 시기와 삭제할 데이터를 적어 주세요. 계정과 다른 이용자를 보호하기 위해 추가 확인을 요청할 수 있습니다.</p></div>
<h2>제한적으로 보관되는 정보</h2><div class="table-wrap"><table><thead><tr><th>정보</th><th>보관기간</th><th>목적</th></tr></thead><tbody><tr><td>신고·제재 증거와 운영 안전 메시지 백업</td><td>생성 또는 마지막 처리일로부터 최대 1년</td><td>안전 운영, 분쟁·법적 요청 대응</td></tr><tr><td>기기 지갑 및 부정 가입 방지 기록</td><td>마지막 이용일 또는 탈퇴일로부터 최대 1년</td><td>포인트 중복 지급과 부정 이용 방지</td></tr><tr><td>법령상 보존 정보</td><td>관계 법령이 정한 기간</td><td>법적 의무 준수</td></tr></tbody></table></div><p>보관 목적이 끝난 정보는 복구할 수 없는 방법으로 삭제합니다.</p><h2>문의</h2><p>이메일: <a href="mailto:itembus@itembus.com">itembus@itembus.com</a> / 전화: <a href="tel:15551645">1555-1645</a></p>
<% End If %></main><!--#include file="_footer.asp"-->
