<%@ Language="VBScript" CodePage="65001" %><% Response.CharSet="utf-8": pageTitleKo="잉톡 개인정보처리방침": pageTitleEn="Ingtalk Privacy Policy": pageDescriptionKo="잉톡 개인정보처리방침": pageDescriptionEn="Ingtalk Privacy Policy and data practices": currentPage="privacy": currentFile="privacy.asp" %><!--#include file="_header.asp"-->
<main id="main" class="container"><% If lang = "en" Then %>
<header class="page-head"><h1>Ingtalk Privacy Policy</h1><p class="effective">Effective date: August 28, 2026</p></header>
<p>Itembus processes personal information for Ingtalk as follows.</p>
<h2>1. Data and purposes</h2>
<p>When you choose Kakao sign-in, Kakao and Supabase Auth process your app-scoped Kakao user ID and authentication session. We do not request your Kakao nickname, profile photo or email. App accounts use a keyed hash of the Kakao ID across devices; Kakao profiles are not copied to public Ingtalk profiles.</p>
<p>When you choose Google sign-in, Google and Supabase Auth process your Google account identifier, email and its verification status, and basic profile information for authentication. Google names, emails, and photos are not automatically copied to your public Ingtalk profile. App accounts use a keyed hash of the stable Google identifier across devices, not email matching. Points and chats are not automatically merged with phone accounts or other sign-in methods.</p>
<p>When you request linking, recent verification of the current account, verification of the additional method, and the registered device are required. Both methods then reference one internal account ID. Similar phone numbers, emails or devices alone never grant another account's data. One-time linking requests expire after 5 minutes and remain for retry-limit enforcement until scheduled cleanup one day after expiration.</p>
<p>Phone numbers and SMS verification records support signup, login and abuse prevention; numbers are not shown to other users. A random device credential is saved in secure device storage; the application database keeps its hash, a keyed phone-number hash and account bindings. Reinstall recovery uses a hash derived from the Android app-scoped device identifier or iPhone Keychain credential. The server stores a further keyed hash until account deletion, never the raw Android device identifier. Supabase Auth processes the actual phone number for SMS authentication. Internal user ID, nickname, age, and gender support profiles, age restrictions, and matching. Talk cards, posts, comments, reactions, chat activity, reports, and blocks support the service, disputes, and safety. Installation ID, app and OS version, push token, access records, and error records support same-number and same-device account verification, notifications, diagnostics, and abuse prevention. Photos and location are processed only when selected. The Google Mobile Ads SDK may automatically collect and share an approximate location inferred from IP address, app interactions such as launches, taps, ad views and video views, SDK diagnostics, and device identifiers such as the advertising ID and app set ID for ad delivery, measurement, analytics, and fraud prevention. Ad completion, ad transaction identifiers, and point-reward records support the 50-point reward, the 24-hour limit, and duplicate-reward prevention.</p>
<p>When you purchase points, RevenueCat and Apple App Store or Google Play process the internal app account ID, product, transaction and receipt identifiers, purchase time, amount, currency, country and refund information to verify purchases, credit points, prevent duplicate grants and handle refunds. Ingtalk does not directly collect card or bank account numbers.</p>
<h2>2. Retention</h2>
<p>Each 50P check-in, rewarded-ad, talk-card, post and comment reward is available once per rolling 24 hours per account and device. To prevent repeat claims after switching accounts, deletion or normal reinstallation, a device hash and the last grant time per reward are retained separately from accounts and cleaned up after seven days. Opaque ad-claim tickets are valid for 24 hours and cleaned up seven days after expiry. Tickets do not contain phone numbers or raw device identifiers.</p>
<p>Kakao authentication records are deleted after all device accounts linked to that Kakao identity are deleted. The keyed Kakao identifier used to prevent repeat welcome grants remains while linked accounts exist, then for up to one year after last use or deletion before scheduled cleanup.</p>
<p>Google authentication records are deleted after all device accounts linked to that Google identity are deleted. The keyed Google identifier used to prevent repeat welcome grants remains while linked accounts exist, then for up to one year after last use or deletion before scheduled cleanup.</p>
<p>Keyed device hashes, welcome-reward usage and registration cooldown timestamps are retained separately to prevent repeat registration and duplicate rewards. After all accounts on that device are deleted, these records remain for up to one year after last use or deletion before scheduled cleanup. Internal authentication identifiers for deletion retries are cleaned up after 30 days once deletion is complete; failed deletions retain the records necessary to finish processing.</p>
<p>Profiles and general service data are kept until account deletion. User-accessible chats are kept up to 30 days; closed support inquiries and error logs up to 90 days; safety and enforcement evidence up to one year; and device-wallet and repeat-registration prevention records up to one year after last use or withdrawal. Phone authentication records are deleted when all device accounts linked to that number have been deleted. A keyed phone hash prevents duplicate welcome grants while linked accounts exist, then is retained up to one year after last use or deletion and removed by scheduled cleanup. The same linked Google or Kakao account can restore the account across devices. Phone recovery also requires a registered device. Losing access to the required method or device identity may prevent restoration. Legally required or disputed records may be isolated for the necessary period and then irreversibly deleted.</p>
<h2>3. Processors and international processing</h2>
<p>RevenueCat, Inc. and the app stores process purchase verification, receipts and refunds. Purchase information may be processed in the United States or other provider infrastructure locations, transferred over encrypted networks when purchases or refunds occur, and retained for legally required periods or dispute handling. RevenueCat privacy policy: https://www.revenuecat.com/privacy/.</p>
<p>Kakao sign-in is optional. Kakao and Supabase Auth process account authentication when selected. Kakao privacy policy: https://www.kakao.com/policy/privacy. You can choose another sign-in method.</p>
<p>Google sign-in is optional. Google's authentication service and Supabase Auth process account authentication information when you choose it. Google's privacy policy is available at https://policies.google.com/privacy. You may choose phone verification instead.</p>
<p>Twilio and delivery carriers process recipient phone numbers, verification messages and delivery status when SMS verification is requested. Processing may occur in the United States or other provider infrastructure locations. Provider terms: https://www.twilio.com/en-us/legal/privacy/faqs and https://www.twilio.com/en-us/legal/data-protection-addendum. Supabase processes authentication, database, storage, and realtime communications in Seoul. Expo/650 Industries, Sentry/Functional Software, Google Firebase, and Google AdMob may process app, device, push-token, error, advertising-interaction, and identifier data in the United States or other infrastructure locations for builds, updates, push delivery, diagnostics, ad delivery, measurement, and fraud prevention. Transfers use encrypted networks. Google's privacy practices are available at https://policies.google.com/privacy. Refusing or restricting related processing may limit push, diagnostics, advertising, or ad-reward features.</p>
<h2>4. Optional permissions</h2>
<p>Location supports distance-based cards; precise coordinates are not shown to users. Notifications announce chat requests and messages. Only photos selected through the system picker are processed. Refusal limits only the related feature.</p>
<h2>5. User rights</h2>
<p>Users may edit profiles, withdraw permissions, or delete their account under My Info. Requests for access, correction, deletion, suspension, or withdrawal may be sent to itembus@itembus.com or 1555-1645.</p>
<h2>6. Minors</h2>
<p>Ingtalk is limited to users age 19 or older. Accounts and content may be restricted or deleted when use by a minor is identified.</p>
<h2>7. Security and deletion</h2>
<p>Protections include encryption in transit, row-level security, separated administrator access, audit logs, reporting, blocking, and enforcement. Electronic files are deleted to prevent recovery; legally retained data is isolated.</p>
<h2>8. Privacy contact</h2>
<p>Email: itembus@itembus.com</p>
<h2>9. Changes</h2>
<p>Changes will be announced in the app or on a public webpage before taking effect.</p>
<% Else %>
<header class="page-head"><h1>잉톡 개인정보처리방침</h1><p class="effective">시행일: 2026년 8월 28일</p></header>
<p>아이템버스는 잉톡 서비스 이용자의 개인정보를 다음과 같이 처리합니다.</p>
<h2>1. 처리 항목과 목적</h2>
<p>카카오 로그인을 선택하면 카카오와 Supabase Auth가 해당 앱의 카카오 회원번호와 인증 세션을 처리합니다. 닉네임·프로필 사진·이메일은 요청하지 않으며, 앱 계정은 카카오 회원번호의 비밀키 기반 해시로 기기와 무관하게 구분합니다. 카카오 프로필을 잉톡 공개 프로필로 가져오지 않습니다.</p>
<p>Google 로그인을 선택하면 Google과 Supabase Auth가 Google 고유 계정 식별자, 이메일 및 이메일 인증 여부, 기본 프로필 정보를 인증 목적으로 처리합니다. Google 이름·이메일·사진은 잉톡 공개 프로필로 자동 복사하지 않습니다. 앱 계정은 이메일 대신 Google 고유 식별자의 비밀키 기반 해시로 기기와 무관하게 구분하며, 전화번호 계정이나 다른 로그인 방식의 포인트·대화와 자동으로 합치지 않습니다.</p>
<p>이용자가 계정 연결을 요청하면 현재 계정의 최근 인증과 추가 로그인 수단의 인증 및 등록 기기 정보를 확인하고, 인증한 로그인 수단을 하나의 내부 계정 식별자에 연결합니다. 전화번호·이메일·기기가 같다는 추측만으로 다른 계정에 접근시키지 않습니다. 연결 확인용 일회성 요청은 5분 동안 유효하며, 재시도 제한을 위해 만료 후 1일까지 보관한 뒤 정기 삭제합니다.</p>
<p>전화번호와 SMS 인증 내역은 가입·로그인과 부정 가입 방지에 사용하며 다른 이용자에게 공개하지 않습니다. 앱이 자동 생성하는 기기 인증 키는 기기의 보안 저장소에 보관하고, 서버에는 그 해시와 전화번호의 비밀키 기반 해시 및 계정 연결 정보만 별도로 보관합니다. 재설치 복구에는 Android의 앱 범위 기기 식별값 또는 iPhone 키체인 인증 정보에서 만든 해시를 사용하고, 서버에는 비밀키로 한 번 더 변환한 복구 식별값을 계정 삭제 시까지 저장합니다. 원래 Android 기기 식별값은 서버로 전송하지 않습니다. 전화번호 원문은 SMS 인증 제공자인 Supabase Auth에서 처리합니다. 필수 정보인 내부 사용자 식별자, 닉네임, 나이와 성별은 프로필 생성, 연령 제한 운영 및 대화 상대 정보 제공에 사용합니다. 대화 카드, 게시글, 댓글, 좋아요, 대화 신청·수락·거절, 메시지, 신고·차단 기록은 서비스 제공, 분쟁 처리와 안전 운영에 사용합니다. 설치 식별자, 앱·OS 버전, 푸시 토큰, 접속·오류 기록은 같은 번호·기기의 계정 확인, 알림, 장애 분석과 부정 이용 방지에 사용합니다. 프로필·게시글 사진과 위치는 이용자가 선택한 경우에만 처리합니다. Google Mobile Ads SDK는 광고 제공, 광고 성과 측정·분석 및 부정 이용 방지를 위해 IP 주소로 추정한 대략적 위치, 앱 실행·탭·광고 및 동영상 조회 같은 앱 상호작용, SDK 진단 정보, 광고 ID·앱 세트 ID 등 기기 식별자를 자동으로 수집·공유할 수 있습니다. 광고 시청 완료 여부, 광고 거래 식별자와 포인트 보상 내역은 50포인트 지급, 24시간 제한 및 중복 보상 방지에 사용합니다.</p>
<p>결제를 선택하면 RevenueCat과 Apple App Store 또는 Google Play가 내부 앱 계정 ID, 상품·거래·영수증 식별자, 구매 시각·금액·통화·국가 및 환불 정보를 처리합니다. 잉톡은 카드번호나 은행 계좌번호를 직접 수집하지 않습니다. 이 정보는 구매 검증, 포인트 지급, 중복 지급 방지 및 환불 처리에 사용합니다.</p>
<h2>2. 보유기간</h2>
<p>출석·광고 시청·톡쓰기·게시글·댓글의 50P 보상은 항목별로 계정과 기기당 마지막 지급 후 24시간에 한 번 지급합니다. 계정 변경·탈퇴·일반적인 재설치로 중복 수령하지 못하도록 기기 식별 해시와 항목별 마지막 지급 시각을 계정과 분리해 보관하고, 지급 후 7일이 지나면 정기 삭제합니다. 광고 보상 확인용 일회성 식별자는 발급 후 24시간 동안 유효하며 만료 후 7일이 지나면 정기 삭제합니다. 이 식별자에 전화번호나 기기 원본 식별값은 포함하지 않습니다.</p>
<p>카카오 인증 정보는 해당 카카오 계정에 연결된 기기 계정이 모두 삭제될 때 삭제합니다. 중복 가입 보상 방지용 카카오 식별자 해시는 연결된 계정이 있는 동안 보관하며, 모두 삭제된 뒤 마지막 이용 또는 탈퇴로부터 최대 1년 후 정기 삭제합니다.</p>
<p>Google 인증 정보는 해당 Google 계정에 연결된 기기 계정이 모두 삭제될 때 삭제합니다. 가입 포인트 중복 지급 방지용 Google 식별자 해시는 연결된 계정이 있는 동안 보관하고, 모두 삭제된 뒤에는 마지막 이용 또는 탈퇴로부터 최대 1년간 보관한 후 정기 삭제합니다.</p>
<p>같은 기기에서 반복 가입과 중복 보상을 방지하기 위한 비밀키 기반 기기 식별 해시·보상 사용 여부·재가입 제한 시점은 계정과 분리하여 보관합니다. 해당 기기의 계정이 모두 삭제된 뒤에는 마지막 이용 또는 탈퇴로부터 최대 1년간 보관한 후 정기 삭제합니다. 계정 삭제 재시도용 내부 인증 식별자는 삭제 완료 후 30일이 지나면 정기 삭제하며, 삭제가 실패한 경우 완료될 때까지 처리에 필요한 기록을 보관합니다.</p>
<p>프로필과 일반 서비스 데이터는 계정 삭제 시까지 보관합니다. 사용자에게 제공되는 채팅은 최대 30일, 종료된 고객센터 문의와 오류 로그는 최대 90일, 신고·제재 증거와 운영 안전을 위한 메시지 백업은 최대 1년, 기기 지갑과 부정 가입 방지 기록은 마지막 이용일 또는 탈퇴일로부터 최대 1년 보관합니다. 관계 법령에 별도 보존 의무가 있거나 분쟁·수사 대응을 위한 보존 조치가 필요한 경우 해당 기간 동안 분리 보관하며, 기간이 끝나면 복구할 수 없는 방법으로 삭제합니다. 전화번호 인증 정보는 해당 번호에 연결된 기기 계정이 모두 탈퇴할 때 삭제합니다. 가입 포인트 중복 지급 방지용 전화번호 해시는 연결된 계정이 있는 동안 보관하고, 연결된 계정이 모두 삭제된 뒤에는 마지막 이용 또는 탈퇴로부터 최대 1년간 보관한 후 정기 삭제합니다. 연결된 Google·카카오 계정은 다른 기기에서도 같은 잉톡 계정·포인트·대화로 로그인합니다. 전화번호 인증은 등록된 기기를 확인해야 기존 계정을 복구합니다. 사용할 수 있는 연결 수단이나 필요한 기기 정보를 잃으면 복구할 수 없습니다.</p>
<h2>3. 처리위탁과 국외 처리</h2>
<p>RevenueCat, Inc.와 앱 스토어는 구매 검증, 영수증 및 환불 처리를 담당합니다. 구매 정보는 구매·환불 발생 시 암호화된 네트워크로 전달되며 미국 등 제공자 인프라 소재지에서 처리될 수 있습니다. 법적 보존 의무나 분쟁 처리에 필요한 기간 동안 보관될 수 있습니다. RevenueCat 개인정보 안내: https://www.revenuecat.com/privacy/.</p>
<p>카카오 로그인은 선택 기능이며 카카오와 Supabase Auth가 계정 인증을 처리합니다. 카카오의 개인정보 처리 기준은 https://www.kakao.com/policy/privacy 에서 확인할 수 있습니다. 원하지 않으면 다른 로그인 수단을 선택할 수 있습니다.</p>
<p>Google 로그인은 이용자가 선택한 경우에만 진행되며 Google의 인증 서비스와 Supabase Auth가 계정 인증 정보를 처리합니다. Google 개인정보 처리 기준은 https://policies.google.com/privacy 에서 확인할 수 있습니다. Google 로그인을 원하지 않으면 전화번호 인증을 선택할 수 있습니다.</p>
<p>Twilio와 문자 전달 통신사업자는 SMS 인증을 위해 수신 전화번호, 인증 문자 내용과 전달 상태를 처리합니다. 이 과정에서 미국 등 제공자의 인프라 소재 국가에서 처리될 수 있으며 전송은 인증 요청 시 이루어집니다. 제공자 처리 기준은 https://www.twilio.com/en-us/legal/privacy/faqs 및 https://www.twilio.com/en-us/legal/data-protection-addendum 에서 확인할 수 있습니다. Supabase는 서울(ap-northeast-2) 리전에서 인증, 데이터베이스, 파일 저장과 실시간 통신을 처리합니다. Expo/650 Industries, Sentry/Functional Software, Google Firebase 및 Google AdMob은 앱 빌드·업데이트·푸시 전달·오류 분석·광고 제공과 측정 과정에서 미국 등 서비스 인프라 소재 국가로 앱·기기·푸시 토큰·오류·광고 상호작용과 식별자 정보를 전송해 처리할 수 있습니다. 전송은 기능 이용 또는 오류 발생 시 암호화된 네트워크로 이루어지며, 각 정보는 본 방침의 보유기간 또는 수탁 계약 종료 시까지 보관됩니다. Google의 개인정보 처리 기준은 https://policies.google.com/privacy 에서 확인할 수 있습니다. 국외 처리에 동의하지 않으면 선택 기능을 사용하지 않거나 고객지원으로 처리정지·삭제를 요청할 수 있으나 푸시 알림, 오류 분석 또는 광고 보상 등 일부 기능이 제한될 수 있습니다.</p>
<h2>4. 선택 권한</h2>
<p>위치는 거리 범위별 대화 카드를 제공하는 데 사용하며 정확한 좌표를 다른 이용자에게 공개하지 않습니다. 알림은 대화 신청과 새 메시지를 알려주는 데 사용합니다. 프로필·게시글 사진은 이용자가 시스템 사진 선택 화면에서 직접 고른 항목만 처리합니다. 위치와 알림을 거부해도 해당 기능 이외의 서비스는 이용할 수 있습니다.</p>
<h2>5. 이용자의 권리</h2>
<p>이용자는 내 정보에서 프로필을 수정하거나 권한을 철회할 수 있고, 내 정보 → 회원 탈퇴에서 계정과 관련 데이터 삭제를 요청할 수 있습니다. 열람, 정정, 삭제, 처리정지와 동의 철회는 itembus@itembus.com 또는 1555-1645로 요청할 수 있습니다.</p>
<h2>6. 미성년자</h2>
<p>잉톡은 만 19세 이상만 이용할 수 있으며 미성년자의 이용이 확인되면 계정과 콘텐츠를 제한 또는 삭제할 수 있습니다.</p>
<h2>7. 안전조치와 파기</h2>
<p>운영자는 전송 구간 암호화, 데이터베이스 행 수준 보안, 운영자 권한 분리와 감사 기록, 신고·차단 및 계정 제재 기능을 적용합니다. 전자적 파일은 복구가 어렵도록 삭제하고 법적 보존 정보는 별도로 분리합니다.</p>
<h2>8. 개인정보 보호 문의</h2>
<p>이메일: itembus@itembus.com</p>
<h2>9. 변경 고지</h2>
<p>본 방침이 변경되면 시행 전에 앱 또는 공개 웹페이지를 통해 알립니다.</p>
<% End If %></main><!--#include file="_footer.asp"-->
