<%@ Language="VBScript" CodePage="65001" %><% Response.CharSet="utf-8": pageTitleKo="잉톡 개인정보처리방침": pageTitleEn="Ingtalk Privacy Policy": pageDescriptionKo="잉톡 개인정보처리방침": pageDescriptionEn="Ingtalk Privacy Policy and data practices": currentPage="privacy": currentFile="privacy.asp" %><!--#include file="_header.asp"-->
<main id="main" class="container"><% If lang="en" Then %>
<header class="page-head"><h1>Ingtalk Privacy Policy</h1><p class="effective">Effective: August 23, 2026</p></header><p>Itembus (the “Operator”) publishes this Privacy Policy to explain how personal data is handled securely in the Ingtalk service.</p>
<h2>1. Data and Purposes</h2><div class="table-wrap"><table><thead><tr><th>Category</th><th>Data</th><th>Purpose</th></tr></thead><tbody><tr><td>Required profile</td><td>Anonymous user ID, nickname, age or birth year, gender, language, and country</td><td>Create profiles, provide conversation-partner information, and enforce age restrictions</td></tr><tr><td>Service activity</td><td>Talk cards, posts, comments, reactions, chat requests and decisions, messages, reports, and blocks</td><td>Provide the service, resolve disputes, and maintain safety</td></tr><tr><td>Optional data</td><td>Profile and post photos, approximate and precise location</td><td>Display selected photos and provide distance-based discovery</td></tr><tr><td>Device and technical data</td><td>Installation ID, app and OS version, push token, access and error logs</td><td>Restore the device wallet, send notifications, diagnose errors, and prevent abuse</td></tr><tr><td>Purchases and rewards</td><td>Store product, transaction and receipt identifiers, currency, points, and reward history</td><td>Verify purchases, provide points, prevent duplicate rewards, and handle refunds</td></tr></tbody></table></div><p>Ingtalk does not currently request contacts, microphone access, or permission to track activity across other apps and websites. Advertising-related disclosures will be updated when an advertising SDK is activated.</p>
<h2>2. Retention</h2><ul><li>Active-account profiles and general service data: until account deletion</li><li>User-accessible chat messages: up to 30 days</li><li>Closed support inquiries and error logs: up to 90 days</li><li>Safety message backups and report or enforcement evidence: up to one year</li><li>Device-wallet and repeat-registration prevention records: up to one year after last use or withdrawal</li><li>Records required by law: for the legally required period</li></ul><p>Expired data is irreversibly deleted. Records needed for a legal obligation, investigation, or dispute may be isolated with restricted access until the required period ends. Anonymous board aliases remain linked to internal identifiers where necessary for safety and legal duties.</p>
<h2>3. Service Providers and International Processing</h2><p>The Operator does not sell personal data or disclose it to third parties except with consent or as required by law. The following providers process data on the Operator's behalf.</p><div class="table-wrap"><table><thead><tr><th>Provider</th><th>Purpose</th><th>Location and data</th></tr></thead><tbody><tr><td>Supabase, Inc.</td><td>Authentication, database, file storage, realtime services, and server functions</td><td>Accounts, profiles, content, messages, and photos / Seoul, Republic of Korea (ap-northeast-2)</td></tr><tr><td>Expo / 650 Industries, Inc.</td><td>Builds, updates, and push notifications</td><td>App, device, and push-token data / United States and other infrastructure locations</td></tr><tr><td>Functional Software, Inc. (Sentry)</td><td>Error reporting and performance diagnostics</td><td>Error, device, app, and limited user-ID data / United States</td></tr><tr><td>Google Firebase</td><td>Android push delivery</td><td>App identifiers and push-related data / United States and other infrastructure locations</td></tr><tr><td>RevenueCat, Inc. and app stores</td><td>Purchase processing and receipt verification</td><td>User ID, product, transaction, receipt, and currency data / provider infrastructure locations</td></tr></tbody></table></div><p>International transfers occur over encrypted networks when a feature is used or an error occurs. Data is retained for the period above or until the processing agreement ends. Users may request restriction or deletion through Support, although this may limit related features.</p>
<h2>4. Location and Optional Permissions</h2><p>Approximate or precise location is used to calculate and display distance ranges. Exact coordinates are not shown to other users. Users can deny location permission and continue using non-location features. Notifications announce chat requests and messages. Only photos explicitly selected through the system picker are processed.</p>
<h2>5. User Rights</h2><p>Users may edit profiles and withdraw permissions under My Info. Accounts and associated data can be deleted under My Info → Delete account. Users can also request access, correction, deletion, restriction, or withdrawal through <a href="<%=LangUrl("deletion.asp")%>">Account &amp; Data Deletion</a>, <a href="mailto:itembus@itembus.com">itembus@itembus.com</a>, or 1555-1645.</p>
<h2>6. Minors</h2><p>Ingtalk is only for users age 19 or older. Accounts and content may be restricted or deleted if use by a minor is identified.</p>
<h2>7. Safeguards and Disposal</h2><p>The Operator applies encryption in transit, database row-level security, separation and auditing of administrative access, reporting, blocking, and account enforcement. Electronic files are deleted in a manner intended to prevent recovery, while legally retained records are kept separately.</p>
<h2>8. Privacy Contact</h2><ul class="contact-list"><li>Privacy officer: Yongil Cho</li><li>Business: Itembus</li><li>Email: <a href="mailto:itembus@itembus.com">itembus@itembus.com</a></li><li>Phone: <a href="tel:15551645">1555-1645</a></li><li>Address: 2F, Suite 215, 4236 Donghae-daero, Sokcho-si, Gangwon State, Republic of Korea</li></ul>
<h2>9. Changes</h2><p>Material changes to this Policy will be announced in the app or on this website before taking effect.</p><h2>10. Remedies</h2><p>Users in the Republic of Korea may contact the Personal Information Infringement Report Center at 118, the Personal Information Dispute Mediation Committee, or another competent authority for advice or dispute resolution.</p>
<% Else %>
<header class="page-head"><h1>잉톡 개인정보처리방침</h1><p class="effective">시행일: 2026년 8월 23일</p></header><p>아이템버스(이하 “운영자”)는 잉톡 서비스 이용자의 개인정보를 안전하게 처리하기 위해 다음과 같이 개인정보처리방침을 공개합니다.</p>
<h2>1. 처리하는 정보와 목적</h2><div class="table-wrap"><table><thead><tr><th>구분</th><th>항목</th><th>목적</th></tr></thead><tbody><tr><td>필수 프로필</td><td>익명 사용자 식별자, 닉네임, 나이·출생연도, 성별, 언어, 국가</td><td>프로필 생성, 대화 상대 정보 제공, 연령 제한 운영</td></tr><tr><td>서비스 활동</td><td>대화 카드, 게시글, 댓글, 좋아요, 대화 신청·수락·거절, 메시지, 신고·차단 기록</td><td>서비스 제공, 분쟁 처리, 안전 운영</td></tr><tr><td>선택 정보</td><td>프로필·게시글 사진, 대략적·정확한 위치정보</td><td>사진 표시, 거리 범위별 대화 카드 제공</td></tr><tr><td>기기·기술 정보</td><td>설치 식별자, 앱 버전, OS, 푸시 토큰, 접속·오류 로그</td><td>기기 지갑 복구, 알림, 장애 분석, 부정 이용 방지</td></tr><tr><td>결제·보상</td><td>스토어 상품, 거래·영수증 식별자, 통화, 포인트 및 보상 내역</td><td>구매 검증, 포인트 지급, 중복 보상 방지, 환불 처리</td></tr></tbody></table></div><p>잉톡은 현재 연락처, 마이크 및 다른 앱·웹사이트에 걸친 활동 추적 권한을 요청하지 않습니다. 광고 SDK가 활성화되면 광고 관련 처리 내역을 갱신합니다.</p>
<h2>2. 보유 및 이용기간</h2><ul><li>활성 계정의 프로필과 일반 서비스 데이터: 계정 삭제 시까지</li><li>이용자에게 표시되는 채팅 메시지: 최대 30일</li><li>종료된 고객센터 문의와 오류 로그: 최대 90일</li><li>운영 안전 메시지 백업과 신고·제재 증거: 생성 또는 마지막 처리일로부터 최대 1년</li><li>기기 지갑 및 부정 가입 방지 기록: 마지막 이용일 또는 탈퇴일로부터 최대 1년</li><li>관계 법령상 보존이 필요한 정보: 해당 법령에서 정한 기간</li></ul><p>보존기간이 끝난 정보는 복구할 수 없는 방법으로 삭제합니다. 법적 의무, 분쟁 또는 수사 대응을 위해 필요한 정보는 해당 기간 동안 접근을 제한하여 분리 보관합니다. 익명 게시판 별칭도 안전과 법적 의무를 위해 내부 식별자와 연결될 수 있습니다.</p>
<h2>3. 제3자 제공 및 처리위탁</h2><p>운영자는 개인정보를 판매하지 않으며, 법령에 근거하거나 별도 동의를 받은 경우를 제외하고 제3자에게 제공하지 않습니다. 다음 사업자가 운영자를 대신해 처리합니다.</p><div class="table-wrap"><table><thead><tr><th>수탁자</th><th>처리 목적</th><th>처리 위치·항목</th></tr></thead><tbody><tr><td>Supabase, Inc.</td><td>인증, DB, 파일 저장, 실시간 통신, 서버 함수</td><td>계정·프로필·콘텐츠·메시지·사진 / 대한민국 서울</td></tr><tr><td>Expo / 650 Industries, Inc.</td><td>앱 빌드, 업데이트, 푸시 알림</td><td>앱·기기·푸시 토큰 / 미국 등</td></tr><tr><td>Functional Software, Inc.(Sentry)</td><td>오류 수집과 성능 진단</td><td>오류, 기기·앱, 제한된 사용자 ID / 미국</td></tr><tr><td>Google Firebase</td><td>Android 푸시 전달</td><td>앱 식별자와 푸시 관련 정보 / 미국 등</td></tr><tr><td>RevenueCat, Inc. 및 앱 스토어</td><td>결제 처리와 영수증 검증</td><td>사용자 ID, 상품·거래·영수증·통화 정보 / 제공자 인프라 소재 국가</td></tr></tbody></table></div><p>국외 처리는 기능 이용 또는 오류 발생 시 암호화된 네트워크로 이루어지며, 정보는 위 보유기간 또는 수탁 계약 종료 시까지 보관됩니다. 고객지원을 통해 처리정지·삭제를 요청할 수 있으나 관련 기능이 제한될 수 있습니다.</p>
<h2>4. 위치정보와 선택 권한</h2><p>대략적 또는 정확한 위치는 거리 구간을 계산하고 표시하는 데 사용하며 정확한 좌표를 다른 이용자에게 공개하지 않습니다. 위치 권한을 거부해도 위치 이외의 기능을 사용할 수 있습니다. 알림은 대화 신청과 새 메시지를 알리고, 사진은 시스템 선택 화면에서 이용자가 직접 고른 항목만 처리합니다.</p>
<h2>5. 이용자의 권리</h2><p>이용자는 내 정보에서 프로필을 수정하거나 권한을 철회할 수 있고, 내 정보 → 회원 탈퇴에서 계정과 관련 데이터를 삭제할 수 있습니다. <a href="<%=LangUrl("deletion.asp")%>">계정 및 데이터 삭제 안내</a>, <a href="mailto:itembus@itembus.com">itembus@itembus.com</a> 또는 1555-1645를 통해 열람·정정·삭제·처리정지·동의 철회를 요청할 수 있습니다.</p>
<h2>6. 미성년자의 개인정보</h2><p>잉톡은 만 19세 이상만 이용할 수 있으며 미성년자의 가입과 이용을 허용하지 않습니다. 미성년자 이용이 확인되면 계정과 콘텐츠를 제한 또는 삭제할 수 있습니다.</p>
<h2>7. 안전조치와 파기</h2><p>운영자는 전송 구간 암호화, 데이터베이스 행 수준 보안, 운영자 권한 분리와 감사 기록, 신고·차단 및 계정 제재 기능을 적용합니다. 전자적 파일은 복구가 어렵도록 삭제하고 법적 보존 정보는 별도로 분리합니다.</p>
<h2>8. 개인정보 보호 문의</h2><ul class="contact-list"><li>개인정보 보호책임자: 조용일</li><li>상호: 아이템버스</li><li>이메일: <a href="mailto:itembus@itembus.com">itembus@itembus.com</a></li><li>연락처: <a href="tel:15551645">1555-1645</a></li><li>주소: 강원특별자치도 속초시 동해대로 4236, 2층 215호</li></ul>
<h2>9. 변경 고지</h2><p>본 방침이 변경되면 시행 전에 앱 또는 본 웹사이트를 통해 알립니다.</p><h2>10. 권익침해 구제</h2><p>개인정보 침해 상담이나 분쟁조정은 개인정보침해 신고센터(국번 없이 118), 개인정보분쟁조정위원회 또는 관계 기관에 요청할 수 있습니다.</p>
<% End If %></main><!--#include file="_footer.asp"-->
