<%@ Language="VBScript" CodePage="65001" %><% Response.CharSet="utf-8": pageTitleKo="잉톡 이용약관": pageTitleEn="Ingtalk Terms of Service": pageDescriptionKo="잉톡 서비스 이용약관": pageDescriptionEn="Terms governing the use of Ingtalk": currentPage="terms": currentFile="terms.asp" %><!--#include file="_header.asp"-->
<main id="main" class="container"><% If lang="en" Then %>
<header class="page-head"><h1>Ingtalk Terms of Service</h1><p class="effective">Effective: August 23, 2026</p></header>
<h2>1. Purpose</h2><p>These Terms govern use of the Ingtalk service provided by Itembus and define the rights and responsibilities of the operator and users.</p>
<h2>2. Eligibility</h2><p>Ingtalk is only for users age 19 or older. By using the service, users confirm that they are at least 19 and must provide an accurate age. Accounts and content may be restricted or deleted if a user provides a false age or is found to be a minor. Users must not impersonate others or abuse rewards and points through multiple accounts.</p>
<h2>3. Service</h2><p>The service includes profiles, distance-based talk cards, chat requests and acceptance, one-to-one chats, an anonymous-alias board, points, reports, and blocks. Features may change for safety, legal compliance, or improvement. Material changes will be announced in the app or on this website.</p>
<h2>4. Points</h2><ul><li>Points are digital units used for service features and cannot be exchanged for cash or property.</li><li>Check-in, talk-card, post, comment, and advertising rewards are granted only at the stated intervals.</li><li>Points obtained through abuse, system errors, or violations may be revoked.</li><li>Payment and refund terms for paid points are disclosed separately.</li></ul>
<h2>5. Prohibited Conduct</h2><ul><li>Use by minors, sexual approaches to minors, or sexual conversations with minors</li><li>Prostitution, compensated dating, illegal recordings, pornography, or requests for such content</li><li>Threats, hate, harassment, stalking, or disclosure of personal data</li><li>Fraud, requests for money, investment or loan solicitation, or contact-harvesting spam</li><li>Misuse of another person's photos, works, or personal data</li><li>Abuse of reports, points, device recovery, or disruption of the service</li><li>Conduct that violates law or the Community Guidelines</li></ul>
<h2>6. Content and Enforcement</h2><p>Users must hold the rights necessary for content they submit. The operator may hide or remove prohibited content and suspend or permanently restrict accounts following reports, automated filters, or safety reviews. Relevant records may be preserved or disclosed in response to an immediate safety risk or lawful request.</p>
<h2>7. Reports and Appeals</h2><p>Posts, comments, users, and chats can be reported in the app. Appeals may be sent to <a href="mailto:itembus@itembus.com">itembus@itembus.com</a>.</p>
<h2>8. Account and Data Deletion</h2><p>Users may request account deletion in the app. User-facing data is deleted, while minimum information required for fraud prevention, reports, legal duties, or disputes may be isolated and retained for the period stated in the Privacy Policy. See <a href="<%=LangUrl("deletion.asp")%>">Account &amp; Data Deletion</a>.</p>
<h2>9. Limitation of Liability</h2><p>The operator does not broker or guarantee offline meetings, financial transactions, or external services between users. Users should use care when sharing personal information or meeting offline. Liability that cannot be excluded by law remains unaffected.</p>
<h2>10. Governing Law</h2><p>These Terms are governed by the laws of the Republic of Korea. Disputes will be handled by a court with jurisdiction under Korean civil procedure law.</p>
<h2>11. Operator</h2><ul class="contact-list"><li>Business: Itembus</li><li>Representative: Yongil Cho</li><li>Address: 2F, Suite 215, 4236 Donghae-daero, Sokcho-si, Gangwon State, Republic of Korea</li><li>Email: <a href="mailto:itembus@itembus.com">itembus@itembus.com</a></li><li>Phone: <a href="tel:15551645">1555-1645</a></li></ul>
<% Else %>
<header class="page-head"><h1>잉톡 이용약관</h1><p class="effective">시행일: 2026년 8월 23일</p></header>
<h2>1. 목적</h2><p>본 약관은 아이템버스가 제공하는 잉톡 서비스의 이용 조건과 운영자 및 이용자의 권리·의무를 정합니다.</p>
<h2>2. 이용 자격</h2><p>잉톡은 만 19세 이상만 이용할 수 있습니다. 서비스 이용에 동의하면 이용자는 본인이 만 19세 이상임을 확인하며 정확한 나이 정보를 입력해야 합니다. 나이를 허위로 입력하거나 미성년자의 이용이 확인되면 계정과 콘텐츠가 제한 또는 삭제될 수 있습니다. 타인의 사진·정보를 도용하거나 여러 계정으로 보상과 포인트를 부정 취득해서는 안 됩니다.</p>
<h2>3. 서비스 내용</h2><p>서비스에는 프로필, 거리 범위별 대화 카드, 대화 신청과 수락, 1:1 대화, 익명 별칭 게시판, 포인트 및 신고·차단 기능이 포함됩니다. 운영자는 안전, 법령 준수 또는 서비스 개선을 위해 기능을 변경할 수 있으며 중요한 변경은 앱 또는 본 웹사이트를 통해 알립니다.</p>
<h2>4. 포인트</h2><ul><li>포인트는 서비스 기능 이용을 위한 전자적 수치이며 현금 또는 재산적 가치로 환급되지 않습니다.</li><li>출석, 대화 카드, 게시글·댓글 작성 및 광고 시청 보상은 정해진 주기에 한 번만 지급됩니다.</li><li>부정 이용, 시스템 오류 또는 약관 위반으로 얻은 포인트는 회수될 수 있습니다.</li><li>유료 포인트의 결제·환불 조건은 별도로 고지합니다.</li></ul>
<h2>5. 금지행위</h2><ul><li>미성년자의 가입, 미성년자 대상 접근 또는 성적 대화</li><li>성매매, 조건만남, 불법 촬영물, 음란물의 게시·전송·요구</li><li>협박, 혐오, 괴롭힘, 스토킹, 개인정보 공개</li><li>사기, 금전 요구, 투자·대출 권유, 외부 연락처 유도형 스팸</li><li>타인의 사진·저작물·개인정보 도용</li><li>신고·포인트·기기 복구 시스템 악용 또는 서비스 방해</li><li>법령이나 커뮤니티 운영정책에 위반되는 행위</li></ul>
<h2>6. 콘텐츠와 운영</h2><p>이용자는 본인이 게시한 콘텐츠에 필요한 권리를 보유해야 합니다. 운영자는 신고 접수, 자동 필터 또는 안전 점검을 통해 위반 콘텐츠를 숨김·삭제하고 계정을 기간 정지 또는 영구 정지할 수 있습니다. 긴급한 위험이나 적법한 요청이 있는 경우 관련 기록을 보존·제공할 수 있습니다.</p>
<h2>7. 신고와 이의제기</h2><p>게시글, 댓글, 이용자 및 대화는 앱 안에서 신고할 수 있습니다. 운영 조치에 대한 이의는 <a href="mailto:itembus@itembus.com">itembus@itembus.com</a>으로 신청할 수 있습니다.</p>
<h2>8. 계정 탈퇴와 데이터</h2><p>이용자는 앱 안에서 계정 삭제를 요청할 수 있습니다. 이용자에게 표시되는 데이터는 삭제되며 사기 방지, 신고 처리, 법적 의무 또는 분쟁 대응에 필요한 최소 정보는 개인정보처리방침에 정한 기간 동안 분리 보관될 수 있습니다. 자세한 방법은 <a href="<%=LangUrl("deletion.asp")%>">계정 및 데이터 삭제 안내</a>에서 확인할 수 있습니다.</p>
<h2>9. 책임의 제한</h2><p>운영자는 이용자 사이의 오프라인 만남, 금전 거래 또는 외부 서비스 이용을 중개하거나 보증하지 않습니다. 이용자는 개인정보 공유와 오프라인 만남에 주의해야 하며 법령상 배제할 수 없는 책임은 제한되지 않습니다.</p>
<h2>10. 준거법과 분쟁</h2><p>본 약관은 대한민국 법령을 따르며 분쟁은 민사소송법상 관할 법원에서 해결합니다.</p>
<h2>11. 운영자 정보</h2><ul class="contact-list"><li>상호: 아이템버스</li><li>대표자: 조용일</li><li>주소: 강원특별자치도 속초시 동해대로 4236, 2층 215호</li><li>이메일: <a href="mailto:itembus@itembus.com">itembus@itembus.com</a></li><li>전화번호: <a href="tel:15551645">1555-1645</a></li></ul>
<% End If %></main><!--#include file="_footer.asp"-->
