-- Private customer-support conversations between one user and authorized operators.

create table if not exists public.support_threads (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null unique references public.profiles(id) on delete cascade,
  status text not null default 'open' check (status in ('open', 'closed')),
  last_message_at timestamptz not null default now(),
  user_last_read_at timestamptz,
  admin_last_read_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.support_messages (
  id bigint generated by default as identity primary key,
  thread_id uuid not null references public.support_threads(id) on delete cascade,
  sender_type text not null check (sender_type in ('user', 'admin')),
  sender_user_id uuid not null,
  body text not null check (char_length(trim(body)) between 1 and 2000),
  created_at timestamptz not null default now()
);

create index if not exists support_threads_last_message_idx on public.support_threads(last_message_at desc);
create index if not exists support_messages_thread_created_idx on public.support_messages(thread_id, created_at);

alter table public.support_threads enable row level security;
alter table public.support_messages enable row level security;

drop policy if exists support_threads_select_own on public.support_threads;
create policy support_threads_select_own on public.support_threads for select to authenticated
using (user_id = auth.uid());

drop policy if exists support_messages_select_own on public.support_messages;
create policy support_messages_select_own on public.support_messages for select to authenticated
using (exists (select 1 from public.support_threads thread where thread.id = thread_id and thread.user_id = auth.uid()));

revoke all on public.support_threads, public.support_messages from anon, authenticated;
grant select on public.support_threads, public.support_messages to authenticated;

create or replace function public.send_support_message(message_body text)
returns uuid language plpgsql security definer set search_path = public as $$
declare thread_uuid uuid; normalized_body text := trim(coalesce(message_body, ''));
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  if char_length(normalized_body) not between 1 and 2000 then raise exception 'invalid_message'; end if;
  if not exists (select 1 from public.profiles where id = auth.uid()) then raise exception 'profile_required'; end if;

  insert into public.support_threads(user_id, status, last_message_at, user_last_read_at, updated_at)
  values (auth.uid(), 'open', now(), now(), now())
  on conflict (user_id) do update set status = 'open', last_message_at = now(), user_last_read_at = now(), updated_at = now()
  returning id into thread_uuid;

  insert into public.support_messages(thread_id, sender_type, sender_user_id, body)
  values (thread_uuid, 'user', auth.uid(), normalized_body);
  return thread_uuid;
end;
$$;

create or replace function public.mark_my_support_read()
returns void language plpgsql security definer set search_path = public as $$
begin
  if auth.uid() is null then raise exception 'authentication_required'; end if;
  update public.support_threads set user_last_read_at = now() where user_id = auth.uid();
end;
$$;

create or replace function public.admin_list_support_threads(status_filter text default null, result_limit integer default 300)
returns table (
  thread_id uuid, user_id uuid, nickname text, status text, last_message text,
  last_sender_type text, unread_by_admin boolean, last_message_at timestamptz,
  created_at timestamptz, updated_at timestamptz
) language plpgsql stable security definer set search_path = public as $$
begin
  if not public.admin_has_role('reviewer') then raise exception 'admin_required'; end if;
  return query
  select thread.id, thread.user_id, profile.nickname, thread.status,
    latest.body, latest.sender_type,
    latest.sender_type = 'user' and (thread.admin_last_read_at is null or latest.created_at > thread.admin_last_read_at),
    thread.last_message_at, thread.created_at, thread.updated_at
  from public.support_threads thread
  join public.profiles profile on profile.id = thread.user_id
  left join lateral (
    select message.body, message.sender_type, message.created_at
    from public.support_messages message where message.thread_id = thread.id
    order by message.created_at desc limit 1
  ) latest on true
  where status_filter is null or thread.status = status_filter
  order by (latest.sender_type = 'user' and (thread.admin_last_read_at is null or latest.created_at > thread.admin_last_read_at)) desc,
           thread.last_message_at desc
  limit least(greatest(coalesce(result_limit, 300), 1), 1000);
end;
$$;

create or replace function public.admin_list_support_messages(target_thread_uuid uuid, result_limit integer default 500)
returns table (message_id bigint, sender_type text, sender_user_id uuid, sender_label text, body text, created_at timestamptz)
language plpgsql security definer set search_path = public as $$
begin
  if not public.admin_has_role('reviewer') then raise exception 'admin_required'; end if;
  if not exists (select 1 from public.support_threads where id = target_thread_uuid) then raise exception 'thread_not_found'; end if;
  update public.support_threads set admin_last_read_at = now() where id = target_thread_uuid;
  return query
  select message.id, message.sender_type, message.sender_user_id,
    case when message.sender_type = 'admin' then coalesce(admin_user.email, '운영자') else coalesce(profile.nickname, '사용자') end,
    message.body, message.created_at
  from public.support_messages message
  left join public.profiles profile on profile.id = message.sender_user_id
  left join public.admin_users admin_record on admin_record.user_id = message.sender_user_id
  left join auth.users admin_user on admin_user.id = admin_record.user_id
  where message.thread_id = target_thread_uuid
  order by message.created_at asc
  limit least(greatest(coalesce(result_limit, 500), 1), 1000);
end;
$$;

create or replace function public.admin_send_support_message(target_thread_uuid uuid, message_body text)
returns void language plpgsql security definer set search_path = public as $$
declare normalized_body text := trim(coalesce(message_body, ''));
begin
  if not public.admin_has_role('reviewer') then raise exception 'admin_required'; end if;
  if char_length(normalized_body) not between 1 and 2000 then raise exception 'invalid_message'; end if;
  if not exists (select 1 from public.support_threads where id = target_thread_uuid) then raise exception 'thread_not_found'; end if;
  insert into public.support_messages(thread_id, sender_type, sender_user_id, body)
  values (target_thread_uuid, 'admin', auth.uid(), normalized_body);
  update public.support_threads set status = 'open', last_message_at = now(), admin_last_read_at = now(), updated_at = now() where id = target_thread_uuid;
end;
$$;

create or replace function public.admin_set_support_status(target_thread_uuid uuid, next_status text)
returns void language plpgsql security definer set search_path = public as $$
begin
  if not public.admin_has_role('reviewer') then raise exception 'admin_required'; end if;
  if next_status not in ('open', 'closed') then raise exception 'invalid_status'; end if;
  update public.support_threads set status = next_status, admin_last_read_at = now(), updated_at = now() where id = target_thread_uuid;
  if not found then raise exception 'thread_not_found'; end if;
end;
$$;

revoke all on function public.send_support_message(text), public.mark_my_support_read(),
  public.admin_list_support_threads(text, integer), public.admin_list_support_messages(uuid, integer),
  public.admin_send_support_message(uuid, text), public.admin_set_support_status(uuid, text) from public, anon, authenticated;
grant execute on function public.send_support_message(text), public.mark_my_support_read(),
  public.admin_list_support_threads(text, integer), public.admin_list_support_messages(uuid, integer),
  public.admin_send_support_message(uuid, text), public.admin_set_support_status(uuid, text) to authenticated;

do $$ begin alter publication supabase_realtime add table public.support_messages;
exception when duplicate_object then null; end $$;
notify pgrst, 'reload schema';
